---
- name: AWS
  hosts: 
    - localhost
  roles:
  tasks:
  - name: Install aws-cli
    ansible.builtin.package:
      name:
        - aws-cli
      state: latest
    become: true
    tags: packages
  - name: Check if saml2aws is already installed
    stat:
      path: /usr/local/bin/saml2aws
    register: is_saml2aws_installed
  - name: saml2aws
    ansible.builtin.shell: |
      CURRENT_VERSION=$(curl -Ls https://api.github.com/repos/Versent/saml2aws/releases/latest | grep 'tag_name' | cut -d'v' -f2 | cut -d'"' -f1)
      wget -c https://github.com/Versent/saml2aws/releases/download/v${CURRENT_VERSION}/saml2aws_${CURRENT_VERSION}_linux_amd64.tar.gz -O - | tar -xzv -C ~/.local/bin
      chmod u+x ~/.local/bin/saml2aws
      hash -r
      saml2aws --version
    delegate_to: localhost
    when: not is_saml2aws_installed.stat.exists
  - name: ensure .zshrc exists
    copy:
      content: ""
      dest: ~/.zshrc
      force: no
      owner: "{{ ansible_user_id }}"
      mode: 0700
