---
- name: Tumbleweed packages
  hosts: 
    - localhost
  roles:
  tasks:
#  - name: Install kde packages
#    ansible.builtin.package:
#      name:
#        - tlp
#      state: absent
#    become: true
#    tags: packages
  - name: Install tumbleweed packages
    ansible.builtin.package:
      name:
        - wget
        - direnv
        - fzf
        - rcm
        - vim
        - vlgothic-fonts
#        - power-profiles-daemon
      state: latest
    become: true
    tags: packages
  - name: kaskpass support
    copy:
      dest: "~/.config/plasma-workspace/env/ssh-add.sh"
      content: |
        #!/bin/sh
        export SSH_ASKPASS=/usr/libexec/ssh/ksshaskpass
        if [ ! -S ~/.ssh/ssh_auth_sock ]; then
          eval "$(ssh-agent -s)"
        fi
      mode: 0755
  - name: Update zsh for ksshaskpass
    lineinfile:
      dest: ~/.zshrc
      regexp: 'export SSH_ASKPASS=/usr/libexec/ssh/ksshaskpass'
      line: 'export SSH_ASKPASS=/usr/libexec/ssh/ksshaskpass'
      create: yes
