---
- name: Workstation
  hosts: 
    - localhost
  roles:
  tasks:
  - name: Install all packages
    ansible.builtin.package:
      name:
        - steam
        - wget
        - direnv
        - fzf
        - keepassxc
        - rcm
        - vim
        - thunderbird
      state: latest
    become: true
    tags: packages
  - name: create directory with parent directories
    file:
      path: "~/.config/autostart-scripts/"
      state: directory
  - name: kaskpass support
    copy:
      dest: "~/.config/autostart-scripts/ssh-add.sh"
      content: |
        #!/bin/sh
        export SSH_ASKPASS=/usr/libexec/ssh/ksshaskpass
        /usr/bin/ssh-add -q ~/.ssh/id_ed25519 < /dev/null
      mode: 0755
