---
- name: Tumbleweed packages
  hosts: 
    - localhost
  roles:
  tasks:
#  - name: Install kde packages
#    ansible.builtin.package:
#      name:
#        - tlp
#      state: absent
#    become: true
#    tags: packages
  - name: Install tumbleweed packages
    ansible.builtin.package:
      name:
        - wget
        - direnv
        - fzf
        - rcm
        - vim
        - vlgothic-fonts
#        - power-profiles-daemon
      state: latest
    become: true
    tags: packages
  - name: create directory with parent directories
    file:
      path: "~/.config/autostart-scripts/"
      state: directory
  - name: kaskpass support
    copy:
      dest: "~/.config/autostart-scripts/ssh-add.sh"
      content: |
        export SSH_ASKPASS=/usr/libexec/ssh/ksshaskpass
        if [ ! -S ~/.ssh/ssh_auth_sock ]; then
          eval "$(ssh-agent -s < /dev/null)" > /dev/null
          ln -sf "$SSH_AUTH_SOCK" ~/.ssh/ssh_auth_sock
          /usr/bin/ssh-add -q ~/.ssh/id_ed25519 < /dev/null
        fi
      mode: 0755
