roles:
  - name: andrewrothstein.starship
    version: v1.0.32
  - name: gantsign.sdkman
    version: 2.0.0
  - name: gantsign.sdkman_init
    version: 1.2.1
  - name: gantsign.inotify
    version: 1.2.1
  - name: gantsign.antigen
    version: 1.4.0
  - name: morgangraphics.ansible_role_nvm
    version: v1.5.0
  - name: robertdebock.npm
    version: 3.1.3
  - name: robertdebock.ulimit
    version: 2.1.1
collections:
  - name: community.general
    version: 4.8.1
