roles:
  - name: andrewrothstein.starship
    version: v1.1.6
  - name: gantsign.sdkman
    version: 2.2.0
  - name: gantsign.sdkman_init
    version: 1.2.2
  - name: gantsign.inotify
    version: 1.2.2
  - name: gantsign.antigen
    version: 1.4.2
  - name: morgangraphics.ansible_role_nvm
    version: v1.5.2
  - name: robertdebock.npm
    version: 3.2.0
  - name: robertdebock.ulimit
    version: 2.1.4
collections:
  - name: community.general
    version: 4.8.1
